### ISSUE TITLE
Should I delete Perl::Critic::Lokku from CPAN?

### ISSUE THREAD

**Issue by Flimm** [lokku/Perl-Critic-Lokku#9]
This module is not maintained any more.

I do not have any kind of access to the GitHub repo https://github.com/lokku/Perl-Critic-Lokku/, or to the GitHub organisation https://github.com/lokku/ . However, I do have access rights to [Perl::Critic::Lokku on CPAN](https://metacpan.org/pod/Perl::Critic::Lokku). I am not maintaining this module any more. Even if I wanted to, I don't think it would be right to continue to maintain a module named after a company (Lokku) that I am not associated with.

Would someone at Lokku be willing to be given admin rights on CPAN to Perl::Critic::Lokku instead of me? Let me know.

If not, I plan to delete Perl::Critic::Lokku from CPAN by 1 July 2021. The code will still be available in archives, and here on GitHub. Anyone at Lokku will be free to upload it again using the same name, I presume.

If someone who isn't from Lokku wants to maintain this module, the code is licensed under the Perl 5 license. So you can fork it and publish it under another name that doesn't include "Lokku".

**Comment by freyfogle** [comment]
Totally agree, it just causes confusion. Lokku no longer exists, and to my knowledge the company that bought the company that bought Lokku doesn't use perl (unfortunately!).

**Comment by Flimm** [comment]
I've schedule Perl::Critic::Lokku for deletion from CPAN on Friday 9th of July 2021.

**Comment by Flimm** [comment]
It's gone from CPAN now.
